# Generated by Django 3.0.7 on 2020-06-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20200617_1756"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="summary",),
    ]
