# Generated by Django 3.0.7 on 2020-06-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_auto_20200621_0929"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
