# Generated by Django 3.0.7 on 2020-06-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_auto_20200621_0942"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="title",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
